### PR TITLE
Make more nice looking

### PR DESCRIPTION
**Pull request by Semigradsky**
Before:
---
image

image

After:
---
image

image

### CODE REVIEW

**Comment by Zverik** [comment]
Looks great, thank you!

**Comment by Zverik** [comment]
I made the full screen width smaller, because reading text at the ful width is unconvenient: 72ce0c93d760254b5489b7c8a79cf2d5f9e16719

**Comment by Semigradsky** [comment]
@Zverik  I found that header collapsing for unauthorized user. Need
```css
.wrapper {
  ...
  overflow: hidden;
}
```
or smth like this

**Comment by Zverik** [comment]
Are you sure? For now the issue I see is that the text is off the header. Will this change fix it?

**Comment by Semigradsky** [comment]
Yeah.

**Comment by Zverik** [comment]
Not in the way I expected:

**Comment by Zverik** [comment]
Here is how it looks for a logged-in user:



I assume this calls for putting these two links in the `.wrapper`?..

**Comment by Semigradsky** [comment]
Maybe for mobile view move user info and login link to top line and others links to bottom?

Like this:
image

image

**Comment by Zverik** [comment]
Fixed in 377f3e0611b7e81062ca1f76d4c1eca6844d5295

**Pull request merged**
