### PR TITLE
Fix translation

### PR DESCRIPTION
**Pull request by Mannivu**
The /lang should return the language selected, so I changed "Ti scriverò in inglese" (I will write to you in English) into "Ti scriverò in italiano" (I will write to you in Italian).

### CODE REVIEW

**Comment by Zverik** [comment]
Hi, thanks for fixing the translation. Could you please do the same at [Transifex](https://www.transifex.com/openstreetmap/osm-streak/dashboard/)? The file you're modifying is generated with it.

**Comment by Mannivu** [comment]
Done!

**Comment by Zverik** [comment]
Thank you! Just updated the translations, should be visible now.

**Comment by Mannivu** [comment]
Yes, it's visible. Thank you. 😄

**Pull request closed without merging**
